[versions]
minecraft = "1.21.5"
yarn = "1.21.5+build.1"
fabric-loader = "0.17.2"
kotlin-loader = "1.13.5+kotlin.2.2.10"
fabric-api = "0.128.2+1.21.5"
kotlin = "2.2.10"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "kotlin-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
